# Generated by Django 4.0 on 2021-12-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
